fes/fes/urls.py
from django.contrib import admin
from django.urls import path, include


"""
Created by Wenqiang Kuang.

This lists all the url groups used by the fes web app. 

management_app is the main application, 
admin is django admin application, 
schedule is external django-scheduler application(only the schedule-api is used),
the login views are derived from admin_entrance app. 
"""

urlpatterns = [
    path('management_app/', include('management_app.urls')),
    path('admin/', admin.site.urls),
    path('schedule/', include('schedule.urls')),
    path('', include('admin_entrance.urls')),
]

fes/management_app/urls.py
from django.urls import path

from . import views

""" 
Created by Wenqiang Kuang on Oct 1st 2018 
The management_app urls

This lists all the url paths used in the web app. 
The jinja template language would get the corresponding view via either "name" or path
e.g. href="{% url 'course_list' %}" makes use of the "name"
     href="/management_app/trainers" makes use of the full path
"""

urlpatterns = [
    path('', views.homepage, name='homepage'),

    # trainer list page
    path('trainers', views.trainers, name='trainer_list'),

    # trainer detail page
    path('trainers/<int:trainer_id>/', views.trainer_detail,
         name='trainer_detail'),

    # trainer timetable page
    path('trainers/<int:trainer_id>/timetable', views.trainer_timetable,
         name='trainer_timetable'),

    # add new trainer page
    path('trainers/new', views.trainer_add, name='trainer_add'),

    # edit a trainer page
    path('trainers/<int:trainer_id>/edit', views.trainer_edit,
         name='trainer_edit'),

    # delete a trainer page
    path('trainers/<int:trainer_id>/delete', views.trainer_delete,
         name='trainer_delete'),

    # course list page
    path('courses', views.courses, name='course_list'),

    # course detail page
    path('courses/<int:course_id>/', views.course_detail, name='course_detail'),

    # add new course page
    path('courses/new', views.course_add, name='course_add'),

    # edit a course page
    path('courses/<int:course_id>/edit', views.course_edit, name='course_edit'),

    # delete a course page
    path('courses/<int:course_id>/delete', views.course_delete,
         name='course_delete'),

    # class list page
    path('classes', views.classes, name='class_list'),

    # class detail page
    path('classes/<int:class_id>/', views.class_detail, name='class_detail'),

    # add new class page
    path('classes/new', views.class_add, name='class_add'),

    # edit a class page
    path('classes/<int:class_id>/edit', views.class_edit, name='class_edit'),

    # delete a class page
    path('classes/<int:class_id>/delete', views.class_delete,
         name='class_delete'),

    # client list page
    path('clients', views.clients, name='client_list'),

    # client detail page
    path('clients/<int:client_id>/', views.client_detail, name='client_detail'),

    # add new client page
    path('clients/new', views.client_add, name='client_add'),

    # edit a client page
    path('clients/<int:client_id>/edit', views.client_edit, name='client_edit'),

    # delete a client page
    path('clients/<int:client_id>/delete', views.client_delete,
         name='client_delete'),

    # qualification list page
    path('qualifications', views.qualifications, name='qualification_list'),

    # qualification detail page
    path('qualifications/<int:qualification_id>/', views.qualification_detail,
         name='qualification_detail'),

    # add new qualification page
    path('qualifications/new', views.qualification_add,
         name='qualification_add'),

    # edit a qualification page
    path('qualifications/<int:qualification_id>/edit', views.qualification_edit,
         name='qualification_edit'),

    # delete a qualification page
    path('qualifications/<int:qualification_id>/delete',
         views.qualification_delete, name='qualification_delete'),

    # inventory items list page
    path('inventoryitems', views.inventoryitems, name='inventoryitem_list'),

    # inventory item detail page
    path('inventoryitems/<item_code>/', views.inventoryitem_detail,
         name='inventoryitem_detail'),

    # add new inventory item page
    path('inventoryitems/new', views.inventoryitem_add,
         name='inventoryitem_add'),

    # edit a inventory item page
    path('inventoryitems/<item_code>/edit', views.inventoryitem_edit,
         name='inventoryitem_edit'),

    # delete an item page
    path('inventoryitems/<item_code>/delete',
         views.inventoryitem_delete, name='inventoryitem_delete'),

    # timesheet search result page
    path('timesheet_search', views.timesheet_search, name='timesheet_search'),

    # interaction between one item and trainers page
    path('iteminteraction/<item_code>/', views.inventory_interaction,
         name='item_interaction'),
]

fes/management_app/models.py
from django.db import models
from schedule.models import Event, Calendar

""" 
Created by Wenqiang Kuang
The management_app models

This defines all the models used to do ORM(object relational mapping), which is used to interact with application data 
from MySQL. 

Every class represents a model, which is a table in the database. 
Many-to-Many relationships are resolved automatically by Django using an associative table. 
"""


class Client(models.Model):
    client_name = models.CharField(max_length=100)
    contact_name = models.CharField(max_length=100)
    contact_email = models.CharField(max_length=100)
    created_time = models.DateTimeField('date added')

    def __str__(self):
        return self.client_name


class ClientAddress(models.Model):
    client = models.OneToOneField(Client, on_delete=models.CASCADE,
                                  primary_key=True, related_name='address')
    street = models.CharField(max_length=50)
    state = models.CharField(max_length=5)
    postcode = models.IntegerField()


class Course(models.Model):
    course_name = models.CharField(max_length=100)
    jsa_required = models.BooleanField()
    attendee_required = models.BooleanField()
    customer_sign_required = models.BooleanField()

    def __str__(self):
        return self.course_name


class Qualification(models.Model):
    qualification_name = models.CharField(max_length=100)
    course_teachable = models.ManyToManyField(Course)

    def __str__(self):
        return self.qualification_name


class Trainer(models.Model):
    trainer_first_name = models.CharField(max_length=50)
    trainer_last_name = models.CharField(max_length=50)
    trainer_register_number = models.CharField(max_length=100)
    trainer_email = models.CharField(max_length=100)
    trainer_work_phone = models.CharField(max_length=20)
    trainer_home_phone = models.CharField(max_length=20)
    trainer_qualification = models.ManyToManyField(Qualification)

    def __str__(self):
        return "%s %s" % (self.trainer_first_name, self.trainer_last_name)


class FesClass(Event):
    class_location = models.CharField(max_length=100)
    class_trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, related_name='fesclass')
    class_client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='fesclass')
    class_course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='fesclass')
    note = models.CharField(max_length=200, null=True, blank=True)
    comments = models.CharField(max_length=200, null=True, blank=True)
    feedback = models.CharField(max_length=200, null=True, blank=True)
    jsa_committed = models.BooleanField(default=False)
    signed = models.BooleanField(default=False)


class Attendee(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    class_attend = models.ForeignKey(FesClass, on_delete=models.CASCADE)
    attended = models.BooleanField(default=False)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)


class TrainerCalendar(Calendar):
    trainer = models.OneToOneField(Trainer, on_delete=models.CASCADE,
                                   primary_key=True, related_name='calendar')


class InventoryItem(models.Model):
    item_code = models.CharField(max_length=50, primary_key=True)
    types = (
        (1, 'Water Extinguisher'),
        (2, 'CO2 Extinguisher'),
        (3, 'Foam Extinguisher')
    )
    status = (
        (1, 'new'),
        (2, 'used'),
        (3, 'exhausted')
    )
    item_type = models.IntegerField(choices=types)
    item_status = models.IntegerField(choices=status)
    item_taken = models.DateTimeField('date taken', null=True)
    taken_trainer = models.ManyToManyField(Trainer,
                                           through='InventoryInteraction')


class InventoryInteraction(models.Model):
    item = models.ForeignKey(InventoryItem, on_delete=models.CASCADE)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)
    taken_date = models.DateTimeField()
    status = (
        (1, 'new'),
        (2, 'used'),
        (3, 'exhausted')
    )
    status_at_that_time = models.IntegerField(choices=status)

fes/management_app/forms.py
from datetimewidget.widgets import DateTimeWidget
from django import forms
from django.forms import formset_factory
from schedule.models import Calendar

from .models import Client, Course, Qualification, Trainer, FesClass, \
    ClientAddress, InventoryItem, Attendee

""" 
Created by Wenqiang Kuang
The management_app forms

This lists all the forms used by templates. User uses forms to submit inputs to make GET/POST requests to the server. 
Each class represents a form, fields are the neeeded inputs.
"""


class NewTrainerForm(forms.ModelForm):
    class Meta:
        model = Trainer
        fields = (
            'trainer_first_name', 'trainer_last_name',
            'trainer_register_number',
            'trainer_email',
            'trainer_work_phone', 'trainer_qualification',)
        widgets = {
            'trainer_qualification': forms.CheckboxSelectMultiple(
                attrs={'class': 'trainer_qualifications'})
        }
        

class NewClientAddressForm(forms.ModelForm):
    class Meta:
        model = ClientAddress
        fields = field = ('street', 'state', 'postcode')


class NewClassForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(NewClassForm, self).__init__(*args, **kwargs)
        self.fields['calendar'].queryset = Calendar.objects.filter(slug="classCalendar")

    class Meta:
        model = FesClass
        fields = (
            'start', 'end', 'class_course', 'title',
            'class_trainer', 'class_client', 'calendar',
            'class_location',)
        widgets = {
            'start': DateTimeWidget(attrs={'id': "start_end"}, usel10n=True,
                                    bootstrap_version=3),
            'end': DateTimeWidget(attrs={'id': "start_end"}, usel10n=True,
                                  bootstrap_version=3),
        }


class NewAttendeeForm(forms.ModelForm):
    class Meta:
        model = Attendee
        fields = ('first_name', 'last_name',)


AttendeeFormSet = formset_factory(NewAttendeeForm)


class NewCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('course_name', 'jsa_required', 'attendee_required',
                  'customer_sign_required')


class NewClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('client_name', 'contact_name', 'contact_email',)


class NewQualificationForm(forms.ModelForm):
    class Meta:
        model = Qualification
        fields = ('qualification_name', 'course_teachable',)
        widgets = {
            'course_teachable': forms.CheckboxSelectMultiple(
                attrs={'class': 'myfieldclass'})
        }


class EditInventoryItemForm(forms.ModelForm):
    class Meta:
        model = InventoryItem
        fields = ('item_status', 'item_taken', 'taken_trainer')
        widgets = {
            'item_taken': DateTimeWidget(attrs={'id': "start_end"},
                                         usel10n=True,
                                         bootstrap_version=3),
            'taken_trainer': forms.CheckboxSelectMultiple()
        }


class NewInventoryItemForm(forms.ModelForm):
    class Meta:
        model = InventoryItem
        fields = ('item_code', 'item_status', 'item_type')

fes/management_app/templates/management_app/class_add_new_class.html
{% extends "management_app/navigation_bar_base.html" %}
{% block extra_head %}
#start_end{
    width: 10%;
}
{% endblock %}
{% block nav-class-new %}

<!--This page inherits from navigation_bar_base. It is used to add classes and edit classes. -->
<div class="w3-container w3-sand w3-center w3-text-black w3-padding-32">
    <h4><b>Classes</b></h4>

    <div class="w3-content w3-justify" style="max-width:600px">
        <hr class="w3-opacity w3-black">
        <hr class="w3-opacity w3-black">

        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ class_form.as_p }}
            {{ class_form.media }}

            <hr class="w3-opacity w3-black">
            <h4>Attendees (fistname lastname)</h4>

            {{ attendee_formset.management_form }}
            {% for attendee_form in attendee_formset %}
                <div class="attendee-formset">
                    {{ attendee_form.first_name }}
                    {{ attendee_form.last_name }}
                </div>
            {% endfor %}

            <br><br>
            <button type="submit" class="save btn btn-default">Save</button>
        </form>

    </div>

</div>


<div class="w3-container w3-sand w3-center w3-text-light-grey w3-padding-32">
    <div class="w3-content w3-justify" style="max-width:600px">
        <hr class="w3-opacity w3-black">
        <hr class="w3-opacity w3-black">
    </div>
</div>


<script>
    $('.attendee-formset').formset({
        addText: 'add attendee',
        deleteText: 'remove'
    });
</script>

{% endblock %}

fes/management_app/templates/management_app/class_detail.html
{% extends "management_app/navigation_bar_base.html" %}

<!--This page inherits from navigation_bar_base. It is used to display class details. -->
{% block nav-class-detail %}
<div class="w3-container w3-sand w3-center w3-text-black w3-padding-32">
    <div class="w3-container w3-sand w3-center w3-text-blue-grey w3-padding-32" style="max-width:100%">
    <h1><b>Class Detail</b></h1>
      <div class="w3-content w3-justify" style="max-width:600px">
          <hr class="w3-opacity w3-blue-grey">
          <hr class="w3-opacity w3-blue-grey">
      </div>
    </div>

    <p><button class="w3-button w3-blue-grey w3-padding-large w3-margin-top w3-margin-bottom"
               OnClick="location.href= '{% url 'class_edit' class.id %}'" style="width:auto;">Edit Class</button></p>
    <hr class="w3-opacity">
    {% if class %}

      <p>Start Time : {{ class.start }}</p>
      <p>End Time: {{ class.end }}</p>

      <hr class="w3-opacity">
      <h4><b>Trainer</b></h4>
      <p>{{ class.class_trainer}}</p>
      <p>{{ class.class_trainer.trainer_register_number}}</p>
      <p>{{ class.class_trainer.trainer_email}}</p>
      <p>{{ class.class_trainer.trainer_work_phone}}</p>

      <hr class="w3-opacity">
      <h4><b>Client</b></h4>
      <p>{{ class.class_client}}</p>
      <p>Contact Name: {{ class.class_client.contact_name}}</p>
      <p>Contact Email: {{ class.class_client.contact_email}}</p>

      <hr class="w3-opacity">
      <h4><b>Attendees</b></h4>
      <table class="w3-table-all w3-hoverable w3-justify w3-content" style="max-width:600px">
            <thead>
              <tr class="w3-light-grey">
                <th>Attendee</th>
                <th>Attended</th>
              </tr>
              </thead>
              {% for attendee in class.attendee_set.all %}
                  <tr>
                    <td>{{ attendee }}</td>
                    <td>{{ attendee.attended }}</td>
                  </tr>
              {% endfor %}
      </table>

      <hr class="w3-opacity">
      <h4><b>Location</b></h4>
      <p>{{ class.class_location}}</p>

      {% else %}
        <p>Something went wrong.</p>
    {% endif %}
    <hr class="w3-opacity">
    <p><button class="w3-button w3-blue-grey w3-padding-large w3-margin-top w3-margin-bottom"
               OnClick="location.href= '{% url 'class_delete' class.id %}'" style="width:auto;">Delete Class</button></p>

    <div class="w3-container w3-sand w3-center w3-text-blue-grey w3-padding-32" style="max-width:100%">
      <div class="w3-content w3-justify" style="max-width:600px">
          <hr class="w3-opacity w3-blue-grey">
          <hr class="w3-opacity w3-blue-grey">
      </div>
    </div>

</div>
{% endblock %}

fes/management_app/templates/management_app/classes.html
{% extends "management_app/navigation_bar_base.html" %}

<!--This page inherits from navigation_bar_base. It is used to display all classes in the data table. -->
{% block nav-classes %}
<div class="w3-container w3-blue-grey w3-center w3-text-light-grey w3-padding-32">
    <h4><b>Classes</b></h4>
    <div class="w3-content w3-justify" style="max-width:600px">
        <hr class="w3-opacity w3-black">
        <hr class="w3-opacity w3-black">
    </div>
    <p><button class="w3-button w3-white w3-padding-large w3-margin-top w3-margin-bottom"
               OnClick="location.href= '{% url 'class_add' %}'" style="width:auto;">Add new Class</button></p>

</div>

<table id="class-list" class="display" style="width:100%">
    <thead>
    <tr>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Client</th>
        <th>Trainer</th>
        <th>Location</th>
        <th>Title</th>
        <th>Course</th>
    </tr>
    </thead>
    <tbody>
    {% if class_list %}
    <tr>
        {% for class in class_list %}
        <td><a href="{% url 'class_detail' class.id %}">{{ class.start}}</a></td>
        <td>{{ class.end }}</td>
        <td>{{ class.fesclass.class_client}}</td>
        <td>{{ class.fesclass.class_trainer}}</td>
        <td>{{ class.fesclass.class_location}}</td>
        <td>{{ class.title}}</td>
        <td><a href="{% url 'course_detail' class.fesclass.class_course_id %}">{{ class.fesclass.class_course }}</a></td>
    </tr>
    {% endfor %}
    {% else %}
    <p>No classes are found.</p>
    {% endif %}
    </tbody>
    <tfoot>
    <tr>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Client</th>
        <th>Trainer</th>
        <th>Location</th>
        <th>Title</th>
        <th>Course</th>
    </tr>
    </tfoot>
</table>

<div class="w3-sand w3-container w3-center w3-text-blue-grey w3-padding-32">
    <div class="w3-content w3-justify" style="max-width:600px">
        <hr class="w3-opacity w3-black">
        <hr class="w3-opacity w3-black">
    </div>
</div>

<script>
    $(function(){
    $("#class-list").dataTable();
    })
</script>

{% endblock %}

fes/management_app/templates/management_app/client_add_new_client.html
{% extends "management_app/navigation_bar_base.html" %}

<!--This page inherits from navigation_bar_base. It is used to add clients and edit clients. -->
{% block nav-client-new %}
<!-- About section -->
<div class="w3-container w3-sand w3-center w3-text-black w3-padding-32">
    <h4><b>Clients</b></h4>
    <div class="w3-content w3-justify" style="max-width:600px">
        <hr class="w3-opacity w3-black">
        <hr class="w3-opacity w3-black">
    </div>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ client_form.as_p }}
        {{ address_form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
</div>


<div class="w3-container w3-sand w3-center w3-text-light-grey w3-padding-32">
    <div class="w3-content w3-justify" style="max-width:600px">
        <hr class="w3-opacity w3-black">
        <hr class="w3-opacity w3-black">
    </div>
</div>

{% endblock %}

fes/management_app/templates/management_app/client_detail.html
{% extends "management_app/navigation_bar_base.html" %}

<!--This page inherits from navigation_bar_base. It is used to display client details. -->
{% block nav-client-detail %}
  <div class="w3-container w3-sand w3-center w3-text-black w3-padding-32">

      <div class="w3-container w3-sand w3-center w3-text-blue-grey w3-padding-32" style="max-width:100%">
      <h4><b>Client Detail</b></h4>
      <div class="w3-content w3-justify" style="max-width:600px">
          <hr class="w3-opacity w3-blue-grey">
          <hr class="w3-opacity w3-blue-grey">
      </div>
    </div>
    <p><button class="w3-button w3-blue-grey w3-padding-large w3-margin-top w3-margin-bottom"
               OnClick="location.href= '{% url 'client_edit' client.id %}'" style="width:auto;">Edit Client</button></p>
    <hr class="w3-opacity">
    {% if client %}

      <p>Client Name : {{ client.client_name }}</p>
      <p>Contact Name: {{ client.contact_name}}</p>
      <p>Contact Email: {{ client.contact_email}}</p>
      <p>Created Time: {{ client.created_time}}</p>

      <hr class="w3-opacity">

      <p>Client Address:  {{ client.address.street }}, {{ client.address.state }}, {{ client.address.postcode }}</p>

      {% else %}
        <p>Something went wrong.</p>
    {% endif %}


    <hr class="w3-opacity">
    <h4><b>All Classes</b></h4>
    <table class="w3-table-all w3-hoverable">
            <thead>
              <tr class="w3-light-grey">
                <th>Start</th>
                <th>End</th>
                <th>Course</th>
                <th>Trainer</th>
                <th>Class Name</th>
              </tr>
              </thead>
              {% if client.fesclass %}
              {% for class in client.fesclass.all %}
                  <tr>
                    <td><a href="{% url 'class_detail' class.id %}"> {{ class.start }} </a></td>
                    <td><a href="{% url 'class_detail' class.id %}"> {{ class.end }}</a></td>
                    <td>{{ class.class_course }}</td>
                    <td>{{ class.class_trainer }}</td>
                    <td>{{ class.title }}</td>
                  </tr>
              {% endfor %}
            {% endif %}
        </table>


    <hr class="w3-opacity">
    <p><button class="w3-button w3-blue-grey w3-padding-large w3-margin-top w3-margin-bottom"
               OnClick="location.href= '{% url 'client_delete' client.id %}'" style="width:auto;">Delete Client</button></p>

    <div class="w3-container w3-sand w3-center w3-text-blue-grey w3-padding-32" style="max-width:100%">
      <div class="w3-content w3-justify" style="max-width:600px">
          <hr class="w3-opacity w3-blue-grey">
          <hr class="w3-opacity w3-blue-grey">
      </div>
    </div>

  </div>
{% endblock %}

fes/management_app/templates/management_app/inventoryitem_detail.html
{% extends "management_app/navigation_bar_base.html" %}

<!--This page inherits from navigation_bar_base. It is used to display inventory item details. -->

{% block nav-inventoryitem-detail %}
<!-- About section -->
  <div class="w3-container w3-sand w3-center w3-text-black w3-padding-32">
    <div class="w3-container w3-sand w3-center w3-text-blue-grey w3-padding-32" style="max-width:100%">
    <h1><b>Inventory Item Detail</b></h1>
      <div class="w3-content w3-justify" style="max-width:600px">
          <hr class="w3-opacity w3-blue-grey">
          <hr class="w3-opacity w3-blue-grey">
      </div>
    </div>

      <p><button class="w3-button w3-blue-grey w3-padding-large w3-margin-top w3-margin-bottom"
               OnClick="location.href= '{% url 'inventoryitem_edit' inventoryitem.item_code %}'" style="width:auto;">Edit Item</button></p>
    <hr class="w3-opacity">
    {% if inventoryitem %}

      <p>Item Code : {{ inventoryitem.item_code }}</p>
      <p>Item Type : {{ inventoryitem.get_item_type_display }}</p>
      <p>Item Status: {{ inventoryitem.get_item_status_display }}</p>
      <p>Last Taken Date: {{ inventoryitem.item_taken}}</p>

      {% else %}
        <p>Something went wrong.</p>
    {% endif %}
    <hr class="w3-opacity">
    <p><button class="w3-button w3-blue-grey w3-padding-large w3-margin-top w3-margin-bottom"
               OnClick="location.href= '{% url 'inventoryitem_delete' inventoryitem.item_code %}'" style="width:auto;">Delete Item</button></p>

    <div class="w3-container w3-sand w3-center w3-text-blue-grey w3-padding-32" style="max-width:100%">
      <div class="w3-content w3-justify" style="max-width:600px">
          <hr class="w3-opacity w3-blue-grey">
          <hr class="w3-opacity w3-blue-grey">
      </div>
    </div>

  </div>
{% endblock %}

fes/management_app/templates/management_app/inventoryitem_interaction_history.html
{% extends "management_app/navigation_bar_base.html" %}

<!--This page inherits from navigation_bar_base. It is used to display inventory items' history. -->

{% block nav-inventoryitem-interaction %}
<div class="w3-container w3-blue-grey w3-center w3-text-light-grey w3-padding-32">
    <h4><b>Interaction History</b></h4>
    <div class="w3-content w3-justify" style="max-width:600px">
        <hr class="w3-opacity w3-black">
        <hr class="w3-opacity w3-black">
    </div>

</div>

<table id="item_history_list" class="display" style="width:100%">
    <thead>
    <tr>
        <th>Item Code</th>
        <th>Taken By</th>
        <th>Item Taken Date</th>
        <th>Item Status at that time</th>
    </tr>
    </thead>
    <tbody>
    {% if item_history_list %}
    <tr>
        {% for history in item_history_list %}
          <td><a href="{% url 'inventoryitem_detail' history.item.item_code %}">{{ history.item.item_code }}</a></td>
          <td><a href="{% url 'trainer_detail' history.trainer.id %}">{{ history.trainer }}</a></td>
          <td>{{ history.taken_date }}</td>
          <td>{{ history.get_status_at_that_time_display }}</td>
    </tr>
    {% endfor %}
    {% else %}
    <p>This item has no interaction history.</p>
    {% endif %}
    </tbody>
    <tfoot>
    <tr>
        <th>Item Code</th>
        <th>Taken By</th>
        <th>Item Taken Date</th>
        <th>Item Status at that time</th>
    </tr>
    </tfoot>
</table>

<div class="w3-sand w3-container w3-center w3-text-blue-grey w3-padding-32">
    <div class="w3-content w3-justify" style="max-width:600px">
        <hr class="w3-opacity w3-black">
        <hr class="w3-opacity w3-black">
    </div>
</div>

<script>
    $(function(){
    $("#item_history_list").dataTable();
    })
</script>

{% endblock %}

fes/management_app/templates/management_app/inventoryitems.html
{% extends "management_app/navigation_bar_base.html" %}

<!--This page inherits from navigation_bar_base. It is used to display inventory items in data table. -->

{% block nav-inventoryitems %}
<div class="w3-container w3-blue-grey w3-center w3-text-light-grey w3-padding-32">
    <h4><b>Inventory Items</b></h4>
    <div class="w3-content w3-justify" style="max-width:600px">
        <hr class="w3-opacity w3-black">
        <hr class="w3-opacity w3-black">
    </div>
    <p><button class="w3-button w3-white w3-padding-large w3-margin-top w3-margin-bottom"
               OnClick="location.href= '{% url 'inventoryitem_add' %}'" style="width:auto;">Add new Item</button></p>

</div>

<table id="inventoryitem_list" class="display" style="width:100%">
    <thead>
    <tr>
        <th>Item Code</th>
        <th>Item Type</th>
        <th>Item Status</th>
        <th>Interaction History</th>
    </tr>
    </thead>
    <tbody>
    {% if inventoryitem_list %}
    <tr>
        {% for item in inventoryitem_list %}
          <td><a href="{% url 'inventoryitem_detail' item.item_code %}">{{ item.item_code }}</a></td>
          <td>{{ item.get_item_type_display }}</td>
          <td>{{ item.get_item_status_display }}</td>
        <td><a href="{% url 'item_interaction' item.item_code %}">{{ item.item_taken }}</a></td>
    </tr>
    {% endfor %}
    {% else %}
    <p>No items are found.</p>
    {% endif %}
    </tbody>
    <tfoot>
    <tr>
        <th>Item Code</th>
        <th>Item Type</th>
        <th>Item Status</th>
        <th>Interaction History</th>
    </tr>
    </tfoot>
</table>

<div class="w3-sand w3-container w3-center w3-text-blue-grey w3-padding-32">
    <div class="w3-content w3-justify" style="max-width:600px">
        <hr class="w3-opacity w3-black">
        <hr class="w3-opacity w3-black">
    </div>
</div>

<script>
    $(function(){
    $("#inventoryitem_list").dataTable();
    })
</script>

{% endblock %}